site_name: TeamUP Documentation

theme:
  name: material
  features:
    - content.action.edit
    - navigation.path
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - search.share
  

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - footnotes
  - tables

plugins:
  - tags
  - search

repo_url: https://github.dxc.com/vkostadinov9/testing_mk-docs
edit_uri: edit/main/docs/

extra_javascript:
  - javascripts/feedback.js

nav:
  - Development Environment Setup:
    - OS Installation: dev_env_setup/os_install.md
    - Requesting Accounts: dev_env_setup/requesting_accs.md
    - MS Office Setup: dev_env_setup/ms_office.md
    - Mail Client Setup: dev_env_setup/mail_setup.md
    - VPN and Secure Gateway: dev_env_setup/vpn.md
    - Phoneless TOTP: dev_env_setup/totp.md
    - OpenShift CLI Setup: dev_env_setup/oc.md
    - Citrix Client Setup: dev_env_setup/citrix.md
    - tox Setup: dev_env_setup/tox_setup.md
    - mvn Setup: dev_env_setup/mvn_setup.md

  - Daily Monitoring Routines:
    - Dashboards: monitoring/dashboards.md
    - Daily Monitoring: monitoring/daily_mon.md

  - Service Now:
    - Information: service_now/intro.md
    - Account Setup: service_now/snow_acc_setup.md
    - Filters and Views: service_now/snow_filters.md
    - Incidents Management: service_now/inc_mgmt.md
    - Incidents Management Process: service_now/inc_mgmt_proc.md

  - RaaS:
    - RaaS:
      - Deployment: raas/raas-deployment.md
      - Rollback: raas/rollback.md
    - Data Quality:
      - Deployment: raas/dq-deployment.md
      - Rollback: raas/rollback.md
    - MapR Tickets: raas/mapr-tickets.md

  - KPI Framework:
    - Deployment: kpi/deployment.md
    - Manual Triggering Smoke and Integration Test: kpi/manually_triggering_kpi_analysis.md
    - Manual Triggering KPI Analysis: kpi/triggering_smoke_integration_tests.md

  - Reference data: todo.md

  - Jenkins:
    - Pipelines: jenkins/raas_kpi_branch_descriptions.md

    